apiVersion: batch/v1
kind: Job
metadata:
  namespace: default
  name: myjob
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - image: cgr.dev/chainguard/cosign:latest-dev@sha256:51208e83fb7db4ecce50fc0e39331c0f6781aba56fc95ef0db4ec9b7a0e41fa5
      - image: cgr.dev/chainguard/python:latest@sha256:2abc89970a8732fcc8f4a5011705a0e823c12c80f4e00e3d322b7c09145a016d
      - image: registry.access.redhat.com/ubi9/openjdk-17-runtime:latest@sha256:3029219b1bf9956f72d1cc7b2da3192c46476aefbb6ca9a850e6a07eaf504374
